name: ci
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          flake8 . --max-line-length=88
          pytest -q || true
      - uses: docker/build-push-action@v5
        with: { push: false, tags: forex-bot-wa:latest }
